namespace CheckinRequestListener
{
    using System;
    using System.Collections.Generic;
    
    // NOTE: This class was automatically generated by InRule irAuthor
    // and may be overwritten in the future.
    // Consider re-generating as a partial class if modifications are required.
    [Serializable()]
    public class JavaIrDistributionResponse
    {
        private string _errorCodes;
        private List<errors> _errors = new List<errors>();
        private string _packageName;
        private List<unsupportedFeatures> _unsupportedFeatures = new List<unsupportedFeatures>();
        private string _type;
        private string _title;
        private int _status;
        public virtual string errorCodes
        {
            get
            {
                return this._errorCodes;
            }
            set
            {
                this._errorCodes = value;
            }
        }
        public virtual List<errors> errors
        {
            get
            {
                return this._errors;
            }
        }
        public virtual string packageName
        {
            get
            {
                return this._packageName;
            }
            set
            {
                this._packageName = value;
            }
        }
        public virtual List<unsupportedFeatures> unsupportedFeatures
        {
            get
            {
                return this._unsupportedFeatures;
            }
        }
        public virtual string type
        {
            get
            {
                return this._type;
            }
            set
            {
                this._type = value;
            }
        }
        public virtual string title
        {
            get
            {
                return this._title;
            }
            set
            {
                this._title = value;
            }
        }
        public virtual int status
        {
            get
            {
                return this._status;
            }
            set
            {
                this._status = value;
            }
        }
    }
    // NOTE: This class was automatically generated by InRule irAuthor
    // and may be overwritten in the future.
    // Consider re-generating as a partial class if modifications are required.
    [Serializable()]
    public class errors
    {
        private string _code;
        private string _description;
        private sourceDef _sourceDef;
        private string _errorMessage;
        public virtual string code
        {
            get
            {
                return this._code;
            }
            set
            {
                this._code = value;
            }
        }
        public virtual string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this._description = value;
            }
        }
        public virtual sourceDef sourceDef
        {
            get
            {
                return this._sourceDef;
            }
            set
            {
                this._sourceDef = value;
            }
        }
        public virtual string errorMessage
        {
            get
            {
                return this._errorMessage;
            }
            set
            {
                this._errorMessage = value;
            }
        }
    }
    // NOTE: This class was automatically generated by InRule irAuthor
    // and may be overwritten in the future.
    // Consider re-generating as a partial class if modifications are required.
    [Serializable()]
    public class sourceDef
    {
        private string _guid;
        private string _path;
        public virtual string guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this._guid = value;
            }
        }
        public virtual string path
        {
            get
            {
                return this._path;
            }
            set
            {
                this._path = value;
            }
        }
    }
    // NOTE: This class was automatically generated by InRule irAuthor
    // and may be overwritten in the future.
    // Consider re-generating as a partial class if modifications are required.
    [Serializable()]
    public class unsupportedFeatures
    {
        private string _feature;
        private List<sourceDefUsages> _sourceDefUsages = new List<sourceDefUsages>();
        public virtual string feature
        {
            get
            {
                return this._feature;
            }
            set
            {
                this._feature = value;
            }
        }
        public virtual List<sourceDefUsages> sourceDefUsages
        {
            get
            {
                return this._sourceDefUsages;
            }
        }
    }
    // NOTE: This class was automatically generated by InRule irAuthor
    // and may be overwritten in the future.
    // Consider re-generating as a partial class if modifications are required.
    [Serializable()]
    public class sourceDefUsages
    {
        private string _guid;
        private string _path;
        public virtual string guid
        {
            get
            {
                return this._guid;
            }
            set
            {
                this._guid = value;
            }
        }
        public virtual string path
        {
            get
            {
                return this._path;
            }
            set
            {
                this._path = value;
            }
        }
    }
}
